In [1]:
import pandas as pd
import numpy as np

Loading the Dataset

In [2]:
df = pd.read_csv("Loan2u.csv")

In [3]:
df

,Customer ID,Name,Gender,Age,Income (USD),Income Stability,Profession,Type of Employment,Location,Loan Amount Request (USD),...,Dependents,Credit Score,No. of Defaults,Has Active Credit Card,Property ID,Property Type,Property Location,Co-Applicant,Property Price (USD),Loan Sanction Amount (USD)
0,C-36995,Frederica Shealy,F,56,1933.050,Low,Working,Sales staff,Semi-Urban,72809.58,...,3.0,809.44,0,Unknown,746,Land,Rural,1,119933.46,54607.18
1,C-33999,America Calderone,M,32,4952.910,Low,Working,Unknown,Semi-Urban,46837.47,...,1.0,780.40,0,Unpossessed,608,Multi-family Home,Rural,1,54791.00,37469.98
2,C-3770,Rosetta Verne,F,65,988.190,High,Pensioner,Unknown,Semi-Urban,45593.04,...,1.0,833.15,0,Unpossessed,546,Multi-family Home,Urban,0,72440.58,36474.43
3,C-26480,Zoe Chitty,F,65,2597.666,High,Pensioner,Unknown,Rural,80057.92,...,2.0,832.70,1,Unpossessed,890,Multi-family Home,Semi-Urban,1,121441.51,56040.54
4,C-23459,Afton Venema,F,31,2614.770,Low,Working,High skill tech staff,Semi-Urban,113858.89,...,2.0,745.55,1,Active,715,Land,Semi-Urban,1,208567.91,74008.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,C-43723,Angelyn Clevenger,M,38,4969.410,Low,Commercial associate,Managers,Urban,76657.90,...,2.0,869.61,0,Unpossessed,566,Land,Urban,1,111096.56,68992.11
29996,C-32511,Silas Slaugh,M,20,1606.880,Low,Working,Laborers,Semi-Urban,66595.14,...,3.0,729.41,0,Inactive,175,Commercial Property,Urban,1,73453.94,46616.60
29997,C-5192,Carmelo Lone,F,49,4036.050,Low,Working,Sales staff,Urban,81410.08,...,2.0,739.82,0,Active,959,Single-family Home,Rural,1,102108.02,61057.56
29998,C-12172,Carolann Osby,M,38,2417.710,Low,Working,Security staff,Semi-Urban,142524.10,...,3.0,677.27,1,Unpossessed,375,Land,Urban,1,168194.47,99766.87
29999,C-33003,Bridget Garibaldi,F,63,3068.240,High,Pensioner,Unknown,Rural,156290.54,...,1.0,815.44,0,Active,344,Commercial Property,Rural,1,194512.60,117217.90

Checking how many columns are present

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Customer ID                  30000 non-null  object
 1   Name                         30000 non-null  object
 2   Gender                       30000 non-null  object
 3   Age                          30000 non-null  int64
 4   Income (USD)                 30000 non-null  float64
 5   Income Stability             30000 non-null  object
 6   Profession                   30000 non-null  object
 7   Type of Employment           30000 non-null  object
 8   Location                     30000 non-null  object
 9   Loan Amount Request (USD)    30000 non-null  float64
 10  Current Loan Expenses (USD)  30000 non-null  float64
 11  Dependents                   30000 non-null  float64
 12  Credit Score                 30000 non-null  float64
 13  No. of Defaults              30000 non-null  int64
 14  Has Active Credit Card       30000 non-null  object
 15  Property ID                  30000 non-null  int64
 16  Property Type                30000 non-null  object
 17  Property Location            30000 non-null  object
 18  Co-Applicant                 30000 non-null  int64
 19  Property Price (USD)         30000 non-null  float64
 20  Loan Sanction Amount (USD)   30000 non-null  float64
dtypes: float64(7), int64(4), object(10)
memory usage: 4.8+ MB

Checking whether Null value is Present

In [5]:
df.isna().sum()

Customer ID                    0
Name                           0
Gender                         0
Age                            0
Income (USD)                   0
Income Stability               0
Profession                     0
Type of Employment             0
Location                       0
Loan Amount Request (USD)      0
Current Loan Expenses (USD)    0
Dependents                     0
Credit Score                   0
No. of Defaults                0
Has Active Credit Card         0
Property ID                    0
Property Type                  0
Property Location              0
Co-Applicant                   0
Property Price (USD)           0
Loan Sanction Amount (USD)     0
dtype: int64

Deleting the rows of Loan Scanction Amount which contains the value 0

In [6]:
df_filtered = df[df['Loan Sanction Amount (USD)'] != 0]

In [7]:
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22135 entries, 0 to 29999
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Customer ID                  22135 non-null  object
 1   Name                         22135 non-null  object
 2   Gender                       22135 non-null  object
 3   Age                          22135 non-null  int64
 4   Income (USD)                 22135 non-null  float64
 5   Income Stability             22135 non-null  object
 6   Profession                   22135 non-null  object
 7   Type of Employment           22135 non-null  object
 8   Location                     22135 non-null  object
 9   Loan Amount Request (USD)    22135 non-null  float64
 10  Current Loan Expenses (USD)  22135 non-null  float64
 11  Dependents                   22135 non-null  float64
 12  Credit Score                 22135 non-null  float64
 13  No. of Defaults              22135 non-null  int64
 14  Has Active Credit Card       22135 non-null  object
 15  Property ID                  22135 non-null  int64
 16  Property Type                22135 non-null  object
 17  Property Location            22135 non-null  object
 18  Co-Applicant                 22135 non-null  int64
 19  Property Price (USD)         22135 non-null  float64
 20  Loan Sanction Amount (USD)   22135 non-null  float64
dtypes: float64(7), int64(4), object(10)
memory usage: 3.7+ MB

In [8]:
df = df_filtered

Descriptive Statistics of the Data

In [9]:
df.describe()

,Age,Income (USD),Loan Amount Request (USD),Current Loan Expenses (USD),Dependents,Credit Score,No. of Defaults,Property ID,Co-Applicant,Property Price (USD),Loan Sanction Amount (USD)
count,22135.000000,22135.000000,22135.000000,22135.000000,22135.000000,22135.000000,22135.000000,22135.000000,22135.000000,22135.00000,22135.000000
mean,40.343754,2496.753781,90351.668496,410.201281,2.226248,756.313277,0.193630,500.533544,0.949898,133362.85981,62616.497041
std,16.194810,1066.828597,57310.821010,201.563142,0.892550,61.103306,0.395151,287.675929,0.218160,82311.19409,38208.296102
min,18.000000,378.760000,6108.050000,33.760000,1.000000,588.170000,0.000000,1.000000,0.000000,30682.10000,4023.180000
25%,25.000000,1719.145000,42009.050000,255.700000,2.000000,708.115000,0.000000,250.000000,1.000000,64689.99500,30848.675000
50%,40.000000,2302.400000,77314.430000,378.340000,2.000000,748.480000,0.000000,500.000000,1.000000,113223.29000,53780.660000
75%,56.000000,3077.900000,123914.080000,527.900000,3.000000,805.540000,0.000000,749.000000,1.000000,184981.55000,87913.920000
max,65.000000,5250.795000,238144.880000,926.311250,10.000000,896.260000,1.000000,999.000000,1.000000,315005.95000,141102.530000

Checking whether there is any Outlier is present or not

In [10]:
#Defining into numeric_cols and categorical_cols inorder to fill the numeric value
numeric_cols = df.select_dtypes(include = np.number).columns.tolist()
categorical_cols = df.select_dtypes(include = "object").columns.tolist()

In [11]:
outliers_df_iq = df

# Identify outliers using IQR method
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    outliers_df_iq = pd.concat([outliers_df_iq, outliers])

# Drop duplicates to ensure each outlier row is only included once
outliers_df_iq = outliers_df_iq.drop_duplicates()

# Create a new DataFrame that excludes these outliers
non_outliers_df_iq = df[~df.index.isin(outliers_df_iq.index)]

print("Non-outliers DataFrame:")
non_outliers_df_iq

Non-outliers DataFrame:

Empty DataFrame
Columns: [Customer ID, Name, Gender, Age, Income (USD), Income Stability, Profession, Type of Employment, Location, Loan Amount Request (USD), Current Loan Expenses (USD), Dependents, Credit Score, No. of Defaults, Has Active Credit Card, Property ID, Property Type, Property Location, Co-Applicant, Property Price (USD), Loan Sanction Amount (USD)]
Index: []

[0 rows x 21 columns]

We can confirm that there is no Outliers present in DataFrame and the DataFrame is well structured

#Stepping into Prediction

In [12]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np

#sklearn
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

#Converting the categorical value into numeric value

In [13]:
df[categorical_cols].describe()

,Customer ID,Name,Gender,Income Stability,Profession,Type of Employment,Location,Has Active Credit Card,Property Type,Property Location
count,22135,22135,22135,22135,22135,22135,22135,22135,22135,22135
unique,22135,22135,3,2,7,19,3,4,4,3
top,C-36995,Frederica Shealy,M,Low,Working,Unknown,Semi-Urban,Active,Single-family Home,Semi-Urban
freq,1,1,11084,19943,12014,5741,15930,7147,5820,7955

In [14]:
df[categorical_cols]

,Customer ID,Name,Gender,Income Stability,Profession,Type of Employment,Location,Has Active Credit Card,Property Type,Property Location
0,C-36995,Frederica Shealy,F,Low,Working,Sales staff,Semi-Urban,Unknown,Land,Rural
1,C-33999,America Calderone,M,Low,Working,Unknown,Semi-Urban,Unpossessed,Multi-family Home,Rural
2,C-3770,Rosetta Verne,F,High,Pensioner,Unknown,Semi-Urban,Unpossessed,Multi-family Home,Urban
3,C-26480,Zoe Chitty,F,High,Pensioner,Unknown,Rural,Unpossessed,Multi-family Home,Semi-Urban
4,C-23459,Afton Venema,F,Low,Working,High skill tech staff,Semi-Urban,Active,Land,Semi-Urban
...,...,...,...,...,...,...,...,...,...,...
29995,C-43723,Angelyn Clevenger,M,Low,Commercial associate,Managers,Urban,Unpossessed,Land,Urban
29996,C-32511,Silas Slaugh,M,Low,Working,Laborers,Semi-Urban,Inactive,Commercial Property,Urban
29997,C-5192,Carmelo Lone,F,Low,Working,Sales staff,Urban,Active,Single-family Home,Rural
29998,C-12172,Carolann Osby,M,Low,Working,Security staff,Semi-Urban,Unpossessed,Land,Urban
29999,C-33003,Bridget Garibaldi,F,High,Pensioner,Unknown,Rural,Active,Commercial Property,Rural

In [15]:
from sklearn.preprocessing import LabelEncoder

# Assuming df is your DataFrame
label_encoder = LabelEncoder()

# Example for 'Gender' column
df['Gender'] = label_encoder.fit_transform(df['Gender'])

<ipython-input-15-05ccb0195774>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender'] = label_encoder.fit_transform(df['Gender'])

In [16]:

df = pd.get_dummies(df, columns=['Income Stability', 'Profession', 'Type of Employment', 'Location', 'Has Active Credit Card', 'Property Type', 'Property Location'], drop_first=True)

In [17]:
df

,Customer ID,Name,Gender,Age,Income (USD),Loan Amount Request (USD),Current Loan Expenses (USD),Dependents,Credit Score,No. of Defaults,...,Location_Semi-Urban,Location_Urban,Has Active Credit Card_Inactive,Has Active Credit Card_Unknown,Has Active Credit Card_Unpossessed,Property Type_Land,Property Type_Multi-family Home,Property Type_Single-family Home,Property Location_Semi-Urban,Property Location_Urban
0,C-36995,Frederica Shealy,0,56,1933.050,72809.58,241.08,3.0,809.44,0,...,True,False,False,True,False,True,False,False,False,False
1,C-33999,America Calderone,1,32,4952.910,46837.47,495.81,1.0,780.40,0,...,True,False,False,False,True,False,True,False,False,False
2,C-3770,Rosetta Verne,0,65,988.190,45593.04,171.95,1.0,833.15,0,...,True,False,False,False,True,False,True,False,False,True
3,C-26480,Zoe Chitty,0,65,2597.666,80057.92,298.54,2.0,832.70,1,...,False,False,False,False,True,False,True,False,True,False
4,C-23459,Afton Venema,0,31,2614.770,113858.89,491.41,2.0,745.55,1,...,True,False,False,False,False,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,C-43723,Angelyn Clevenger,1,38,4969.410,76657.90,722.34,2.0,869.61,0,...,False,True,False,False,True,True,False,False,False,True
29996,C-32511,Silas Slaugh,1,20,1606.880,66595.14,253.04,3.0,729.41,0,...,True,False,True,False,False,False,False,False,False,True
29997,C-5192,Carmelo Lone,0,49,4036.050,81410.08,583.11,2.0,739.82,0,...,False,True,False,False,False,False,False,True,False,False
29998,C-12172,Carolann Osby,1,38,2417.710,142524.10,378.29,3.0,677.27,1,...,True,False,False,False,True,True,False,False,False,True
29999,C-33003,Bridget Garibaldi,0,63,3068.240,156290.54,693.94,1.0,815.44,0,...,False,False,False,False,False,False,False,False,False,False

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22135 entries, 0 to 29999
Data columns (total 49 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Customer ID                               22135 non-null  object
 1   Name                                      22135 non-null  object
 2   Gender                                    22135 non-null  int64
 3   Age                                       22135 non-null  int64
 4   Income (USD)                              22135 non-null  float64
 5   Loan Amount Request (USD)                 22135 non-null  float64
 6   Current Loan Expenses (USD)               22135 non-null  float64
 7   Dependents                                22135 non-null  float64
 8   Credit Score                              22135 non-null  float64
 9   No. of Defaults                           22135 non-null  int64
 10  Property ID                               22135 non-null  int64
 11  Co-Applicant                              22135 non-null  int64
 12  Property Price (USD)                      22135 non-null  float64
 13  Loan Sanction Amount (USD)                22135 non-null  float64
 14  Income Stability_Low                      22135 non-null  bool
 15  Profession_Commercial associate           22135 non-null  bool
 16  Profession_Maternity leave                22135 non-null  bool
 17  Profession_Pensioner                      22135 non-null  bool
 18  Profession_State servant                  22135 non-null  bool
 19  Profession_Unemployed                     22135 non-null  bool
 20  Profession_Working                        22135 non-null  bool
 21  Type of Employment_Cleaning staff         22135 non-null  bool
 22  Type of Employment_Cooking staff          22135 non-null  bool
 23  Type of Employment_Core staff             22135 non-null  bool
 24  Type of Employment_Drivers                22135 non-null  bool
 25  Type of Employment_HR staff               22135 non-null  bool
 26  Type of Employment_High skill tech staff  22135 non-null  bool
 27  Type of Employment_IT staff               22135 non-null  bool
 28  Type of Employment_Laborers               22135 non-null  bool
 29  Type of Employment_Low-skill Laborers     22135 non-null  bool
 30  Type of Employment_Managers               22135 non-null  bool
 31  Type of Employment_Medicine staff         22135 non-null  bool
 32  Type of Employment_Private service staff  22135 non-null  bool
 33  Type of Employment_Realty agents          22135 non-null  bool
 34  Type of Employment_Sales staff            22135 non-null  bool
 35  Type of Employment_Secretaries            22135 non-null  bool
 36  Type of Employment_Security staff         22135 non-null  bool
 37  Type of Employment_Unknown                22135 non-null  bool
 38  Type of Employment_Waiters/barmen staff   22135 non-null  bool
 39  Location_Semi-Urban                       22135 non-null  bool
 40  Location_Urban                            22135 non-null  bool
 41  Has Active Credit Card_Inactive           22135 non-null  bool
 42  Has Active Credit Card_Unknown            22135 non-null  bool
 43  Has Active Credit Card_Unpossessed        22135 non-null  bool
 44  Property Type_Land                        22135 non-null  bool
 45  Property Type_Multi-family Home           22135 non-null  bool
 46  Property Type_Single-family Home          22135 non-null  bool
 47  Property Location_Semi-Urban              22135 non-null  bool
 48  Property Location_Urban                   22135 non-null  bool
dtypes: bool(35), float64(7), int64(5), object(2)
memory usage: 3.3+ MB

Converting Boolean value into Numerical Value

In [19]:

boolean_cols = df.select_dtypes(include='bool').columns

df[boolean_cols] = df[boolean_cols].astype(int)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22135 entries, 0 to 29999
Data columns (total 49 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Customer ID                               22135 non-null  object
 1   Name                                      22135 non-null  object
 2   Gender                                    22135 non-null  int64
 3   Age                                       22135 non-null  int64
 4   Income (USD)                              22135 non-null  float64
 5   Loan Amount Request (USD)                 22135 non-null  float64
 6   Current Loan Expenses (USD)               22135 non-null  float64
 7   Dependents                                22135 non-null  float64
 8   Credit Score                              22135 non-null  float64
 9   No. of Defaults                           22135 non-null  int64
 10  Property ID                               22135 non-null  int64
 11  Co-Applicant                              22135 non-null  int64
 12  Property Price (USD)                      22135 non-null  float64
 13  Loan Sanction Amount (USD)                22135 non-null  float64
 14  Income Stability_Low                      22135 non-null  int64
 15  Profession_Commercial associate           22135 non-null  int64
 16  Profession_Maternity leave                22135 non-null  int64
 17  Profession_Pensioner                      22135 non-null  int64
 18  Profession_State servant                  22135 non-null  int64
 19  Profession_Unemployed                     22135 non-null  int64
 20  Profession_Working                        22135 non-null  int64
 21  Type of Employment_Cleaning staff         22135 non-null  int64
 22  Type of Employment_Cooking staff          22135 non-null  int64
 23  Type of Employment_Core staff             22135 non-null  int64
 24  Type of Employment_Drivers                22135 non-null  int64
 25  Type of Employment_HR staff               22135 non-null  int64
 26  Type of Employment_High skill tech staff  22135 non-null  int64
 27  Type of Employment_IT staff               22135 non-null  int64
 28  Type of Employment_Laborers               22135 non-null  int64
 29  Type of Employment_Low-skill Laborers     22135 non-null  int64
 30  Type of Employment_Managers               22135 non-null  int64
 31  Type of Employment_Medicine staff         22135 non-null  int64
 32  Type of Employment_Private service staff  22135 non-null  int64
 33  Type of Employment_Realty agents          22135 non-null  int64
 34  Type of Employment_Sales staff            22135 non-null  int64
 35  Type of Employment_Secretaries            22135 non-null  int64
 36  Type of Employment_Security staff         22135 non-null  int64
 37  Type of Employment_Unknown                22135 non-null  int64
 38  Type of Employment_Waiters/barmen staff   22135 non-null  int64
 39  Location_Semi-Urban                       22135 non-null  int64
 40  Location_Urban                            22135 non-null  int64
 41  Has Active Credit Card_Inactive           22135 non-null  int64
 42  Has Active Credit Card_Unknown            22135 non-null  int64
 43  Has Active Credit Card_Unpossessed        22135 non-null  int64
 44  Property Type_Land                        22135 non-null  int64
 45  Property Type_Multi-family Home           22135 non-null  int64
 46  Property Type_Single-family Home          22135 non-null  int64
 47  Property Location_Semi-Urban              22135 non-null  int64
 48  Property Location_Urban                   22135 non-null  int64
dtypes: float64(7), int64(40), object(2)
memory usage: 8.4+ MB

In [21]:
#Moving the Target col to last
df["Loan Sanction Amount (USD)"] = df.pop("Loan Sanction Amount (USD)")

#Splitting Our data into Train , Test

Splitting the data to input and output

In [22]:
y = df["Loan Sanction Amount (USD)"]
x = df.drop(columns=["Customer ID", "Name", "Loan Sanction Amount (USD)"])

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x , y , test_size = 0.2 , random_state = 42)

In [24]:
x_train.shape , x_test.shape , y_train.shape , y_test.shape

((17708, 46), (4427, 46), (17708,), (4427,))

In [25]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = StandardScaler()

# Fit and transform the training data
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.fit_transform(x_test)

y_train_scaled = scaler.fit_transform(y_train.values.reshape(-1, 1))
y_test_scaled = scaler.fit_transform(y_test.values.reshape(-1, 1))

# Convert scaled data back to DataFrame
x_train = pd.DataFrame(x_train_scaled, columns=x_train.columns)
y_train = pd.DataFrame(y_train_scaled, columns=['Loan Sanction Amount (USD)'])
x_test = pd.DataFrame(x_test_scaled, columns=x_test.columns)
y_test = pd.DataFrame(y_test_scaled, columns=['Loan Sanction Amount (USD)'])

#Load the Dataset

In [26]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset,DataLoader

In [27]:
class CustomDataset(Dataset):
    def __init__(self, data, label):
        self.data = torch.tensor(data.values).type(torch.float32)
        self.label = torch.tensor(label.values).type(torch.float32).view(-1, 1)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        return self.data[index], self.label[index]

In [28]:
dataset = CustomDataset(x_train , y_train)

In [29]:
batch_size = 2
train_loader = DataLoader(dataset , batch_size = batch_size , shuffle = True)

In [30]:
class NeuralNetworks(nn.Module):
    def __init__(self, in_features, out_features, hidden_units):
        super().__init__()
        self.in_features = in_features  # Store input features
        self.layer = nn.Sequential(
            nn.Linear(in_features=in_features, out_features=hidden_units),
            nn.ReLU(),
            nn.Linear(in_features=hidden_units, out_features=hidden_units),
            nn.ReLU(),
            nn.Linear(in_features=hidden_units, out_features=out_features)
        )

    def forward(self, x):
        return self.layer(x)

In [31]:
in_features = x_train.shape[1]
out_features = 1
print(in_features)
model = NeuralNetworks(in_features = in_features , out_features = out_features , hidden_units = 100)

46

In [32]:
loss_fn = nn.MSELoss()
optimizer = torch.optim.Adam(params = model.parameters() , lr = 0.001)

Function to find Mean Absolute Error

In [33]:
def mean_absolute_error(preds, targets):
    return torch.abs(preds - targets).mean()

Training the Model

In [34]:
from tqdm.auto import tqdm
#Random Seed
torch.manual_seed(42)

epochs = 10

for epoch in tqdm(range(epochs)):
    model.train()
    epoch_loss = 0
    epoch_mae = 0
    for input, target in train_loader:
        # Forward pass
        train_logits = model(input)

        # Calculate the loss
        train_loss = loss_fn(train_logits, target)
        epoch_loss += train_loss.item()

        # Calculate MAE
        train_mae = mean_absolute_error(train_logits, target)
        epoch_mae += train_mae.item()

        # Optimizer steps
        optimizer.zero_grad()
        train_loss.backward()
        optimizer.step()

    avg_epoch_loss = epoch_loss / len(train_loader)
    avg_epoch_mae = epoch_mae / len(train_loader)
    print(f'Epoch: {epoch+1}, Train Loss: {avg_epoch_loss:.4f}, Train MAE: {avg_epoch_mae:.4f}')

# Print final training loss and MAE
print(f'Final Train Loss: {avg_epoch_loss:.4f}, Final Train MAE: {avg_epoch_mae:.4f}')

  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 1, Train Loss: 0.0880, Train MAE: 0.1736
Epoch: 2, Train Loss: 0.0865, Train MAE: 0.1368
Epoch: 3, Train Loss: 0.0634, Train MAE: 0.1306
Epoch: 4, Train Loss: 0.0600, Train MAE: 0.1261
Epoch: 5, Train Loss: 0.0579, Train MAE: 0.1237
Epoch: 6, Train Loss: 0.0551, Train MAE: 0.1224
Epoch: 7, Train Loss: 0.0539, Train MAE: 0.1217
Epoch: 8, Train Loss: 0.0535, Train MAE: 0.1200
Epoch: 9, Train Loss: 0.0521, Train MAE: 0.1186
Epoch: 10, Train Loss: 0.0507, Train MAE: 0.1166
Final Train Loss: 0.0507, Final Train MAE: 0.1166

Testing the test Dataset

In [35]:

test_dataset = CustomDataset(x_test, y_test)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

model.eval()
test_loss = 0
test_mae = 0
with torch.no_grad():
    for input, target in test_loader:
        test_logits = model(input)
        loss = loss_fn(test_logits, target)
        mae = mean_absolute_error(test_logits, target)
        test_loss += loss.item()
        test_mae += mae.item()

avg_test_loss = test_loss / len(test_loader)
avg_test_mae = test_mae / len(test_loader)
print(f'Test Loss: {avg_test_loss:.4f}, Test MAE: {avg_test_mae:.4f}')

Test Loss: 0.0662, Test MAE: 0.1204

#Loading the Loan1 Dataset for prediction

In [36]:
df_1 = pd.read_csv("Loan1u.csv")

In [37]:
df_1

,Customer ID,Name,Gender,Age,Income (USD),Income Stability,Profession,Type of Employment,Location,Loan Amount Request (USD),...,Dependents,Credit Score,No. of Defaults,Has Active Credit Card,Property ID,Property Age,Property Type,Property Location,Co-Applicant,Property Price (USD)
0,C-26247,Tandra Olszewski,F,47,3472.69000,Low,Commercial associate,Managers,Semi-Urban,137088.98,...,2.0,799.14000,0,Unpossessed,843,3472.69,Multi-family Home,Urban,1,236644.50
1,C-35067,Jeannette Cha,F,57,1184.84000,Low,Working,Sales staff,Rural,104771.59,...,2.0,833.31000,0,Unpossessed,22,1184.84,Single-family Home,Rural,1,142357.30
2,C-34590,Keva Godfrey,F,52,1266.27000,Low,Working,Unknown,Semi-Urban,176684.91,...,3.0,627.44000,0,Unpossessed,1,1266.27,Single-family Home,Urban,1,300991.24
3,C-16668,Elva Sackett,M,65,1369.72000,High,Pensioner,Unknown,Rural,97009.18,...,2.0,833.20000,0,Inactive,730,1369.72,Single-family Home,Semi-Urban,0,125612.10
4,C-12196,Sade Constable,F,60,1939.23000,High,Pensioner,Unknown,Urban,109980.00,...,4.5,489.50375,0,374,356,1939.23,Land,Semi-Urban,1,180908.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,C-9076,Tobias Davilla,F,19,1349.60000,Low,Commercial associate,Unknown,Semi-Urban,156766.97,...,4.0,684.32000,0,Inactive,681,1349.60,Land,Semi-Urban,1,212778.00
19996,C-17587,Evelina Hodges,M,22,2019.78000,Low,Working,Core staff,Urban,47924.80,...,4.5,706.34000,0,Inactive,213,2019.78,Land,Urban,1,90816.95
19997,C-46479,Karlyn Mckinzie,M,19,2252.03000,Low,Working,Core staff,Semi-Urban,18629.88,...,1.0,656.46000,0,Inactive,270,2252.03,Multi-family Home,Rural,0,21566.27
19998,C-3099,Mariana Pulver,F,21,1845.35000,Low,Working,Unknown,Semi-Urban,95430.73,...,2.0,865.46000,0,Unpossessed,489,1845.35,Single-family Home,Semi-Urban,1,120281.17
19999,C-43482,Mechelle Boddie,M,21,5217.72875,Low,Working,Laborers,Semi-Urban,107966.03,...,3.0,857.16000,1,Active,368,5233.16,Land,Semi-Urban,0,133425.43

In [38]:
df_1.isna().sum()

Customer ID                    0
Name                           0
Gender                         0
Age                            0
Income (USD)                   0
Income Stability               0
Profession                     0
Type of Employment             0
Location                       0
Loan Amount Request (USD)      0
Current Loan Expenses (USD)    0
Dependents                     0
Credit Score                   0
No. of Defaults                0
Has Active Credit Card         0
Property ID                    0
Property Age                   0
Property Type                  0
Property Location              0
Co-Applicant                   0
Property Price (USD)           0
dtype: int64

In [39]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Customer ID                  20000 non-null  object
 1   Name                         20000 non-null  object
 2   Gender                       20000 non-null  object
 3   Age                          20000 non-null  int64
 4   Income (USD)                 20000 non-null  float64
 5   Income Stability             20000 non-null  object
 6   Profession                   20000 non-null  object
 7   Type of Employment           20000 non-null  object
 8   Location                     20000 non-null  object
 9   Loan Amount Request (USD)    20000 non-null  float64
 10  Current Loan Expenses (USD)  20000 non-null  float64
 11  Dependents                   20000 non-null  float64
 12  Credit Score                 20000 non-null  float64
 13  No. of Defaults              20000 non-null  int64
 14  Has Active Credit Card       20000 non-null  object
 15  Property ID                  20000 non-null  int64
 16  Property Age                 20000 non-null  float64
 17  Property Type                20000 non-null  object
 18  Property Location            20000 non-null  object
 19  Co-Applicant                 20000 non-null  int64
 20  Property Price (USD)         20000 non-null  float64
dtypes: float64(7), int64(4), object(10)
memory usage: 3.2+ MB

In [40]:

numeric_cols = df_1.select_dtypes(include = np.number).columns.tolist()
categorical_cols = df_1.select_dtypes(include = "object").columns.tolist()

In [41]:
label_encoder = LabelEncoder()

df_1['Gender'] = label_encoder.fit_transform(df_1['Gender'])

In [42]:

df_1 = pd.get_dummies(df_1, columns=['Income Stability', 'Profession', 'Type of Employment', 'Location', 'Has Active Credit Card', 'Property Type', 'Property Location'], drop_first=True)

In [43]:
df_1

,Customer ID,Name,Gender,Age,Income (USD),Loan Amount Request (USD),Current Loan Expenses (USD),Dependents,Credit Score,No. of Defaults,...,Location_Urban,Has Active Credit Card_Active,Has Active Credit Card_Inactive,Has Active Credit Card_Unpossessed,Property Type_Land,Property Type_Multi-family Home,Property Type_Single-family Home,Property Location_Rural,Property Location_Semi-Urban,Property Location_Urban
0,C-26247,Tandra Olszewski,0,47,3472.69000,137088.98,396.72,2.0,799.14000,0,...,False,False,False,True,False,True,False,False,False,True
1,C-35067,Jeannette Cha,0,57,1184.84000,104771.59,463.76,2.0,833.31000,0,...,False,False,False,True,False,False,True,True,False,False
2,C-34590,Keva Godfrey,0,52,1266.27000,176684.91,493.15,3.0,627.44000,0,...,False,False,False,True,False,False,True,False,False,True
3,C-16668,Elva Sackett,1,65,1369.72000,97009.18,446.15,2.0,833.20000,0,...,False,False,True,False,False,False,True,False,True,False
4,C-12196,Sade Constable,0,60,1939.23000,109980.00,370.10,4.5,489.50375,0,...,True,False,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,C-9076,Tobias Davilla,0,19,1349.60000,156766.97,500.59,4.0,684.32000,0,...,False,False,True,False,True,False,False,False,True,False
19996,C-17587,Evelina Hodges,1,22,2019.78000,47924.80,243.02,4.5,706.34000,0,...,True,False,True,False,True,False,False,False,False,True
19997,C-46479,Karlyn Mckinzie,1,19,2252.03000,18629.88,101.88,1.0,656.46000,0,...,False,False,True,False,False,True,False,True,False,False
19998,C-3099,Mariana Pulver,0,21,1845.35000,95430.73,271.31,2.0,865.46000,0,...,False,False,False,True,False,False,True,False,True,False
19999,C-43482,Mechelle Boddie,1,21,5217.72875,107966.03,922.59,3.0,857.16000,1,...,False,True,False,False,True,False,False,False,True,False

In [44]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 50 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Customer ID                               20000 non-null  object
 1   Name                                      20000 non-null  object
 2   Gender                                    20000 non-null  int64
 3   Age                                       20000 non-null  int64
 4   Income (USD)                              20000 non-null  float64
 5   Loan Amount Request (USD)                 20000 non-null  float64
 6   Current Loan Expenses (USD)               20000 non-null  float64
 7   Dependents                                20000 non-null  float64
 8   Credit Score                              20000 non-null  float64
 9   No. of Defaults                           20000 non-null  int64
 10  Property ID                               20000 non-null  int64
 11  Property Age                              20000 non-null  float64
 12  Co-Applicant                              20000 non-null  int64
 13  Property Price (USD)                      20000 non-null  float64
 14  Income Stability_Low                      20000 non-null  bool
 15  Profession_Maternity leave                20000 non-null  bool
 16  Profession_Pensioner                      20000 non-null  bool
 17  Profession_State servant                  20000 non-null  bool
 18  Profession_Student                        20000 non-null  bool
 19  Profession_Unemployed                     20000 non-null  bool
 20  Profession_Working                        20000 non-null  bool
 21  Type of Employment_Cleaning staff         20000 non-null  bool
 22  Type of Employment_Cooking staff          20000 non-null  bool
 23  Type of Employment_Core staff             20000 non-null  bool
 24  Type of Employment_Drivers                20000 non-null  bool
 25  Type of Employment_HR staff               20000 non-null  bool
 26  Type of Employment_High skill tech staff  20000 non-null  bool
 27  Type of Employment_IT staff               20000 non-null  bool
 28  Type of Employment_Laborers               20000 non-null  bool
 29  Type of Employment_Low-skill Laborers     20000 non-null  bool
 30  Type of Employment_Managers               20000 non-null  bool
 31  Type of Employment_Medicine staff         20000 non-null  bool
 32  Type of Employment_Private service staff  20000 non-null  bool
 33  Type of Employment_Realty agents          20000 non-null  bool
 34  Type of Employment_Sales staff            20000 non-null  bool
 35  Type of Employment_Secretaries            20000 non-null  bool
 36  Type of Employment_Security staff         20000 non-null  bool
 37  Type of Employment_Unknown                20000 non-null  bool
 38  Type of Employment_Waiters/barmen staff   20000 non-null  bool
 39  Location_Semi-Urban                       20000 non-null  bool
 40  Location_Urban                            20000 non-null  bool
 41  Has Active Credit Card_Active             20000 non-null  bool
 42  Has Active Credit Card_Inactive           20000 non-null  bool
 43  Has Active Credit Card_Unpossessed        20000 non-null  bool
 44  Property Type_Land                        20000 non-null  bool
 45  Property Type_Multi-family Home           20000 non-null  bool
 46  Property Type_Single-family Home          20000 non-null  bool
 47  Property Location_Rural                   20000 non-null  bool
 48  Property Location_Semi-Urban              20000 non-null  bool
 49  Property Location_Urban                   20000 non-null  bool
dtypes: bool(36), float64(7), int64(5), object(2)
memory usage: 2.8+ MB

In [45]:

boolean_cols = df_1.select_dtypes(include='bool').columns

df_1[boolean_cols] = df_1[boolean_cols].astype(int)

In [46]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 50 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Customer ID                               20000 non-null  object
 1   Name                                      20000 non-null  object
 2   Gender                                    20000 non-null  int64
 3   Age                                       20000 non-null  int64
 4   Income (USD)                              20000 non-null  float64
 5   Loan Amount Request (USD)                 20000 non-null  float64
 6   Current Loan Expenses (USD)               20000 non-null  float64
 7   Dependents                                20000 non-null  float64
 8   Credit Score                              20000 non-null  float64
 9   No. of Defaults                           20000 non-null  int64
 10  Property ID                               20000 non-null  int64
 11  Property Age                              20000 non-null  float64
 12  Co-Applicant                              20000 non-null  int64
 13  Property Price (USD)                      20000 non-null  float64
 14  Income Stability_Low                      20000 non-null  int64
 15  Profession_Maternity leave                20000 non-null  int64
 16  Profession_Pensioner                      20000 non-null  int64
 17  Profession_State servant                  20000 non-null  int64
 18  Profession_Student                        20000 non-null  int64
 19  Profession_Unemployed                     20000 non-null  int64
 20  Profession_Working                        20000 non-null  int64
 21  Type of Employment_Cleaning staff         20000 non-null  int64
 22  Type of Employment_Cooking staff          20000 non-null  int64
 23  Type of Employment_Core staff             20000 non-null  int64
 24  Type of Employment_Drivers                20000 non-null  int64
 25  Type of Employment_HR staff               20000 non-null  int64
 26  Type of Employment_High skill tech staff  20000 non-null  int64
 27  Type of Employment_IT staff               20000 non-null  int64
 28  Type of Employment_Laborers               20000 non-null  int64
 29  Type of Employment_Low-skill Laborers     20000 non-null  int64
 30  Type of Employment_Managers               20000 non-null  int64
 31  Type of Employment_Medicine staff         20000 non-null  int64
 32  Type of Employment_Private service staff  20000 non-null  int64
 33  Type of Employment_Realty agents          20000 non-null  int64
 34  Type of Employment_Sales staff            20000 non-null  int64
 35  Type of Employment_Secretaries            20000 non-null  int64
 36  Type of Employment_Security staff         20000 non-null  int64
 37  Type of Employment_Unknown                20000 non-null  int64
 38  Type of Employment_Waiters/barmen staff   20000 non-null  int64
 39  Location_Semi-Urban                       20000 non-null  int64
 40  Location_Urban                            20000 non-null  int64
 41  Has Active Credit Card_Active             20000 non-null  int64
 42  Has Active Credit Card_Inactive           20000 non-null  int64
 43  Has Active Credit Card_Unpossessed        20000 non-null  int64
 44  Property Type_Land                        20000 non-null  int64
 45  Property Type_Multi-family Home           20000 non-null  int64
 46  Property Type_Single-family Home          20000 non-null  int64
 47  Property Location_Rural                   20000 non-null  int64
 48  Property Location_Semi-Urban              20000 non-null  int64
 49  Property Location_Urban                   20000 non-null  int64
dtypes: float64(7), int64(41), object(2)
memory usage: 7.6+ MB

In [49]:
scaler_x = StandardScaler().fit(x_train)
scaler_y = StandardScaler().fit(y_train.values.reshape(-1, 1))

In [55]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
import torch

columns_to_drop = ["Customer ID", "Name", "Loan Sanction Amount (USD)"]
x_new = df_1.drop(columns=columns_to_drop, errors='ignore')

train_columns = scaler_x.feature_names_in_
missing_cols = set(train_columns) - set(x_new.columns)

for col in missing_cols:
    x_new[col] = 0

x_new = x_new[train_columns]

x_new_scaled = scaler_x.transform(x_new)

x_new_scaled_df = pd.DataFrame(x_new_scaled, columns=x_new.columns)

x_new_tensor = torch.tensor(x_new_scaled_df.values).type(torch.float32)

model.eval()
with torch.no_grad():
    predictions = model(x_new_tensor).numpy()

predictions_original_scale = scaler_y.inverse_transform(predictions)

df_1['Predicted Loan Sanction Amount (USD)'] = predictions_original_scale

df_1.to_csv('path_to_output_csv.csv', index=False)

print("x_new_tensor shape:", x_new_tensor.shape)
print("Model input features:", model.in_features)

x_new_tensor shape: torch.Size([20000, 46])
Model input features: 46

In [52]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 51 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Customer ID                               20000 non-null  object
 1   Name                                      20000 non-null  object
 2   Gender                                    20000 non-null  int64
 3   Age                                       20000 non-null  int64
 4   Income (USD)                              20000 non-null  float64
 5   Loan Amount Request (USD)                 20000 non-null  float64
 6   Current Loan Expenses (USD)               20000 non-null  float64
 7   Dependents                                20000 non-null  float64
 8   Credit Score                              20000 non-null  float64
 9   No. of Defaults                           20000 non-null  int64
 10  Property ID                               20000 non-null  int64
 11  Property Age                              20000 non-null  float64
 12  Co-Applicant                              20000 non-null  int64
 13  Property Price (USD)                      20000 non-null  float64
 14  Income Stability_Low                      20000 non-null  int64
 15  Profession_Maternity leave                20000 non-null  int64
 16  Profession_Pensioner                      20000 non-null  int64
 17  Profession_State servant                  20000 non-null  int64
 18  Profession_Student                        20000 non-null  int64
 19  Profession_Unemployed                     20000 non-null  int64
 20  Profession_Working                        20000 non-null  int64
 21  Type of Employment_Cleaning staff         20000 non-null  int64
 22  Type of Employment_Cooking staff          20000 non-null  int64
 23  Type of Employment_Core staff             20000 non-null  int64
 24  Type of Employment_Drivers                20000 non-null  int64
 25  Type of Employment_HR staff               20000 non-null  int64
 26  Type of Employment_High skill tech staff  20000 non-null  int64
 27  Type of Employment_IT staff               20000 non-null  int64
 28  Type of Employment_Laborers               20000 non-null  int64
 29  Type of Employment_Low-skill Laborers     20000 non-null  int64
 30  Type of Employment_Managers               20000 non-null  int64
 31  Type of Employment_Medicine staff         20000 non-null  int64
 32  Type of Employment_Private service staff  20000 non-null  int64
 33  Type of Employment_Realty agents          20000 non-null  int64
 34  Type of Employment_Sales staff            20000 non-null  int64
 35  Type of Employment_Secretaries            20000 non-null  int64
 36  Type of Employment_Security staff         20000 non-null  int64
 37  Type of Employment_Unknown                20000 non-null  int64
 38  Type of Employment_Waiters/barmen staff   20000 non-null  int64
 39  Location_Semi-Urban                       20000 non-null  int64
 40  Location_Urban                            20000 non-null  int64
 41  Has Active Credit Card_Active             20000 non-null  int64
 42  Has Active Credit Card_Inactive           20000 non-null  int64
 43  Has Active Credit Card_Unpossessed        20000 non-null  int64
 44  Property Type_Land                        20000 non-null  int64
 45  Property Type_Multi-family Home           20000 non-null  int64
 46  Property Type_Single-family Home          20000 non-null  int64
 47  Property Location_Rural                   20000 non-null  int64
 48  Property Location_Semi-Urban              20000 non-null  int64
 49  Property Location_Urban                   20000 non-null  int64
 50  Predicted Loan Sanction Amount (USD)      20000 non-null  float32
dtypes: float32(1), float64(7), int64(41), object(2)
memory usage: 7.7+ MB

In [56]:
df_1

,Customer ID,Name,Gender,Age,Income (USD),Loan Amount Request (USD),Current Loan Expenses (USD),Dependents,Credit Score,No. of Defaults,...,Has Active Credit Card_Active,Has Active Credit Card_Inactive,Has Active Credit Card_Unpossessed,Property Type_Land,Property Type_Multi-family Home,Property Type_Single-family Home,Property Location_Rural,Property Location_Semi-Urban,Property Location_Urban,Predicted Loan Sanction Amount (USD)
0,C-26247,Tandra Olszewski,0,47,3472.69000,137088.98,396.72,2.0,799.14000,0,...,0,0,1,0,1,0,0,0,1,38334.390625
1,C-35067,Jeannette Cha,0,57,1184.84000,104771.59,463.76,2.0,833.31000,0,...,0,0,1,0,0,1,1,0,0,27896.560547
2,C-34590,Keva Godfrey,0,52,1266.27000,176684.91,493.15,3.0,627.44000,0,...,0,0,1,0,0,1,0,0,1,49270.480469
3,C-16668,Elva Sackett,1,65,1369.72000,97009.18,446.15,2.0,833.20000,0,...,0,1,0,0,0,1,0,1,0,25698.341797
4,C-12196,Sade Constable,0,60,1939.23000,109980.00,370.10,4.5,489.50375,0,...,0,0,0,1,0,0,0,1,0,30389.117188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,C-9076,Tobias Davilla,0,19,1349.60000,156766.97,500.59,4.0,684.32000,0,...,0,1,0,1,0,0,0,1,0,41716.917969
19996,C-17587,Evelina Hodges,1,22,2019.78000,47924.80,243.02,4.5,706.34000,0,...,0,1,0,1,0,0,0,0,1,13771.517578
19997,C-46479,Karlyn Mckinzie,1,19,2252.03000,18629.88,101.88,1.0,656.46000,0,...,0,1,0,0,1,0,1,0,0,4857.119629
19998,C-3099,Mariana Pulver,0,21,1845.35000,95430.73,271.31,2.0,865.46000,0,...,0,0,1,0,0,1,0,1,0,25216.751953
19999,C-43482,Mechelle Boddie,1,21,5217.72875,107966.03,922.59,3.0,857.16000,1,...,1,0,0,1,0,0,0,1,0,28394.152344

#Adding Predicted Loan Sanction Amount into CSV file

In [58]:
original_df = pd.read_csv('Loan1u.csv')

In [59]:
predictions_df = pd.DataFrame(predictions, columns=['Predicted Loan Sanction Amount (USD)'])

In [60]:
updated_df = pd.concat([original_df, predictions_df], axis=1)

In [61]:
updated_df

,Customer ID,Name,Gender,Age,Income (USD),Income Stability,Profession,Type of Employment,Location,Loan Amount Request (USD),...,Credit Score,No. of Defaults,Has Active Credit Card,Property ID,Property Age,Property Type,Property Location,Co-Applicant,Property Price (USD),Predicted Loan Sanction Amount (USD)
0,C-26247,Tandra Olszewski,F,47,3472.69000,Low,Commercial associate,Managers,Semi-Urban,137088.98,...,799.14000,0,Unpossessed,843,3472.69,Multi-family Home,Urban,1,236644.50,38334.390625
1,C-35067,Jeannette Cha,F,57,1184.84000,Low,Working,Sales staff,Rural,104771.59,...,833.31000,0,Unpossessed,22,1184.84,Single-family Home,Rural,1,142357.30,27896.560547
2,C-34590,Keva Godfrey,F,52,1266.27000,Low,Working,Unknown,Semi-Urban,176684.91,...,627.44000,0,Unpossessed,1,1266.27,Single-family Home,Urban,1,300991.24,49270.480469
3,C-16668,Elva Sackett,M,65,1369.72000,High,Pensioner,Unknown,Rural,97009.18,...,833.20000,0,Inactive,730,1369.72,Single-family Home,Semi-Urban,0,125612.10,25698.341797
4,C-12196,Sade Constable,F,60,1939.23000,High,Pensioner,Unknown,Urban,109980.00,...,489.50375,0,374,356,1939.23,Land,Semi-Urban,1,180908.00,30389.117188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,C-9076,Tobias Davilla,F,19,1349.60000,Low,Commercial associate,Unknown,Semi-Urban,156766.97,...,684.32000,0,Inactive,681,1349.60,Land,Semi-Urban,1,212778.00,41716.917969
19996,C-17587,Evelina Hodges,M,22,2019.78000,Low,Working,Core staff,Urban,47924.80,...,706.34000,0,Inactive,213,2019.78,Land,Urban,1,90816.95,13771.517578
19997,C-46479,Karlyn Mckinzie,M,19,2252.03000,Low,Working,Core staff,Semi-Urban,18629.88,...,656.46000,0,Inactive,270,2252.03,Multi-family Home,Rural,0,21566.27,4857.119629
19998,C-3099,Mariana Pulver,F,21,1845.35000,Low,Working,Unknown,Semi-Urban,95430.73,...,865.46000,0,Unpossessed,489,1845.35,Single-family Home,Semi-Urban,1,120281.17,25216.751953
19999,C-43482,Mechelle Boddie,M,21,5217.72875,Low,Working,Laborers,Semi-Urban,107966.03,...,857.16000,1,Active,368,5233.16,Land,Semi-Urban,0,133425.43,28394.152344

In [62]:
updated_df.to_csv('Loan1u.csv', index=False)